## Logistic regression
- Linear classification model<br><br>
Problem: Company XYZ has launched a new SUV and based on prev data, manager wants to predict if a customer will buy this new SUV or not.<br>
Here we have age and estimated salary of customer as independent variables. Purchase is target/dependent varaible with binary value 0 and 1

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('Social_Network_Ads.csv')
data.head()

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0


In [4]:
# drop unnecessary column - giving no info
data = data.drop('User ID', axis=1)
data.head()

,Gender,Age,EstimatedSalary,Purchased
0,Male,19,19000,0
1,Male,35,20000,0
2,Female,26,43000,0
3,Female,27,57000,0
4,Male,19,76000,0


In [5]:
X = data.iloc[:,:-1].values
Y = data.iloc[:,-1].values

print(X.shape)
print(Y.shape)

(400, 3)
(400,)


In [6]:
print(X)

[['Male' 19 19000]
 ['Male' 35 20000]
 ['Female' 26 43000]
 ...
 ['Female' 50 20000]
 ['Male' 36 33000]
 ['Female' 49 36000]]


### check missing values

In [7]:
print(data.isnull().sum())

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64


### Splitting Dataset

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [9]:
print(X_train)

[['Male' 58 144000]
 ['Female' 59 83000]
 ['Female' 24 55000]
 ['Female' 26 35000]
 ['Female' 58 38000]
 ['Female' 42 80000]
 ['Female' 40 75000]
 ['Male' 59 130000]
 ['Female' 46 41000]
 ['Female' 41 60000]
 ['Male' 42 64000]
 ['Female' 37 146000]
 ['Female' 23 48000]
 ['Male' 25 33000]
 ['Male' 24 84000]
 ['Female' 27 96000]
 ['Male' 23 63000]
 ['Male' 48 33000]
 ['Male' 48 90000]
 ['Male' 42 104000]
 ['Female' 44 39000]
 ['Male' 32 120000]
 ['Female' 38 50000]
 ['Female' 32 135000]
 ['Female' 52 21000]
 ['Female' 53 104000]
 ['Male' 39 42000]
 ['Male' 38 61000]
 ['Female' 36 50000]
 ['Female' 36 63000]
 ['Female' 35 25000]
 ['Male' 35 50000]
 ['Male' 42 73000]
 ['Female' 47 49000]
 ['Female' 59 29000]
 ['Male' 49 65000]
 ['Female' 45 131000]
 ['Female' 31 89000]
 ['Female' 46 82000]
 ['Female' 47 51000]
 ['Male' 26 15000]
 ['Male' 60 102000]
 ['Female' 38 112000]
 ['Male' 40 107000]
 ['Female' 42 53000]
 ['Male' 35 59000]
 ['Male' 48 41000]
 ['Female' 48 134000]
 ['Female' 38 113000

In [10]:
print(X_train.shape)
print(X_test.shape)

(320, 3)
(80, 3)


### Categorical column encoding

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64 
 2   EstimatedSalary  400 non-null    int64 
 3   Purchased        400 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 12.6+ KB


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

CT = ColumnTransformer(
    transformers = [
        ('encoder', OneHotEncoder(drop='first', sparse=False), [0])
    ],
    remainder = 'passthrough'
)

fit_transform done on training data, while transform done on test dataset

In [13]:
X_train = CT.fit_transform(X_train)
X_test = CT.transform(X_test)

c:\Users\gusai\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [14]:
print(X_train)

[[1.0 58 144000]
 [0.0 59 83000]
 [0.0 24 55000]
 [0.0 26 35000]
 [0.0 58 38000]
 [0.0 42 80000]
 [0.0 40 75000]
 [1.0 59 130000]
 [0.0 46 41000]
 [0.0 41 60000]
 [1.0 42 64000]
 [0.0 37 146000]
 [0.0 23 48000]
 [1.0 25 33000]
 [1.0 24 84000]
 [0.0 27 96000]
 [1.0 23 63000]
 [1.0 48 33000]
 [1.0 48 90000]
 [1.0 42 104000]
 [0.0 44 39000]
 [1.0 32 120000]
 [0.0 38 50000]
 [0.0 32 135000]
 [0.0 52 21000]
 [0.0 53 104000]
 [1.0 39 42000]
 [1.0 38 61000]
 [0.0 36 50000]
 [0.0 36 63000]
 [0.0 35 25000]
 [1.0 35 50000]
 [1.0 42 73000]
 [0.0 47 49000]
 [0.0 59 29000]
 [1.0 49 65000]
 [0.0 45 131000]
 [0.0 31 89000]
 [0.0 46 82000]
 [0.0 47 51000]
 [1.0 26 15000]
 [1.0 60 102000]
 [0.0 38 112000]
 [1.0 40 107000]
 [0.0 42 53000]
 [1.0 35 59000]
 [1.0 48 41000]
 [0.0 48 134000]
 [0.0 38 113000]
 [1.0 29 148000]
 [0.0 26 15000]
 [1.0 60 42000]
 [1.0 24 19000]
 [1.0 42 149000]
 [0.0 46 96000]
 [1.0 28 59000]
 [1.0 39 96000]
 [1.0 28 89000]
 [1.0 41 72000]
 [1.0 45 26000]
 [0.0 33 69000]
 [0.0 20 

### Feature scaling

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

Scale all column except first, as it is category column and scaling it will loose it's meaning.<br>
Also apply fit_transform on X_train and only on X_test to avoid data leakage.

In [16]:
X_train[:, 1:] = scaler.fit_transform(X_train[:, 1:])
X_test[:, 1:] = scaler.transform(X_test[:, 1:])

In [17]:
print(X_train)

[[1.0 1.9229500774458068 2.146015658291428]
 [0.0 2.020160823856969 0.37871929707771346]
 [0.0 -1.3822153005337159 -0.43249870479087665]
 [0.0 -1.187793807711391 -1.0119401346970125]
 [0.0 1.9229500774458068 -0.9250239202110921]
 [0.0 0.3675781348672079 0.29180308259179305]
 [0.0 0.17315664204488307 0.14694272511525913]
 [1.0 2.020160823856969 1.7404066573571326]
 [0.0 0.7564211205118576 -0.8381077057251717]
 [0.0 0.2703673884560455 -0.28763834731434273]
 [1.0 0.3675781348672079 -0.17175006133311557]
 [0.0 -0.11847559718860422 2.2039598012820414]
 [0.0 -1.4794260469448783 -0.6353032052580242]
 [1.0 -1.2850045541225534 -1.069884277687626]
 [1.0 -1.3822153005337159 0.40769136857302024]
 [0.0 -1.0905830613002285 0.7553562265167018]
 [1.0 -1.4794260469448783 -0.20072213282842236]
 [1.0 0.9508426133341825 -1.069884277687626]
 [1.0 0.9508426133341825 0.5815237975448609]
 [1.0 0.3675781348672079 0.987132798479156]
 [0.0 0.5619996276895328 -0.8960518487157852]
 [1.0 -0.6045293292444164 1.45068

### Training Logistic Regression model

In [18]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, Y_train)

LogisticRegression()

In [19]:
# predicting test set results
y_pred = classifier.predict(X_test)
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 1 1]


### Predict new data
- predict if a female customer of age 27 with salary 97000 will buy the new SUV car or not

- new data must be passed in same way as it is trained

In [20]:
# new_data = pd.DataFrame(
#     [['Female', 27, 97000]],
#     columns=['Gender', 'Age', 'EstimatedSalary']  # must match your training columns
# )
# print(new_data)

new_data = np.array([['Female', 27, 97000]], dtype=object)
print(new_data)

[['Female' 27 97000]]


In [21]:
new_data_encoded = CT.transform(new_data)
print(new_data_encoded)

[[0.0 27 97000]]


In [23]:
# scale it
scaled_data = scaler.transform(new_data_encoded[:,1:])
print(scaled_data)

[[-1.09058306  0.7843283 ]]


In [24]:
final_data = np.concatenate(
    [new_data_encoded[:,:1], scaled_data], axis=1
)
print(final_data)

[[0.0 -1.0905830613002285 0.7843282980120085]]


In [26]:
result = classifier.predict(final_data)
print(f'Model predicted {result}. Customer will not buy SUV')

Model predicted [0]. Customer will not buy SUV
