## Naive Bayes

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Social_Network_Ads.csv')
data.head()

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0


In [3]:
# remove userID column
data = data.drop('User ID', axis= 1)
data.head()

,Gender,Age,EstimatedSalary,Purchased
0,Male,19,19000,0
1,Male,35,20000,0
2,Female,26,43000,0
3,Female,27,57000,0
4,Male,19,76000,0


In [4]:
X = data.iloc[:, :-1].values
Y = data.iloc[:, -1].values

print(X.shape)
print(Y.shape)

(400, 3)
(400,)


In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=0)

print(X_train.shape)
print(X_test.shape)

(320, 3)
(80, 3)


In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

CT = ColumnTransformer(
    transformers = [
        ('encoder', OneHotEncoder(drop='first', sparse=False), [0]),
        ('scaler', StandardScaler(), [1,2])
    ]
)

In [7]:
# Fit it in X_train and transform both X_train and X_test
X_train = CT.fit_transform(X_train)
X_test = CT.transform(X_test)

c:\Users\gusai\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [8]:
print(X_train)

[[ 1.00000000e+00  1.92295008e+00  2.14601566e+00]
 [ 0.00000000e+00  2.02016082e+00  3.78719297e-01]
 [ 0.00000000e+00 -1.38221530e+00 -4.32498705e-01]
 [ 0.00000000e+00 -1.18779381e+00 -1.01194013e+00]
 [ 0.00000000e+00  1.92295008e+00 -9.25023920e-01]
 [ 0.00000000e+00  3.67578135e-01  2.91803083e-01]
 [ 0.00000000e+00  1.73156642e-01  1.46942725e-01]
 [ 1.00000000e+00  2.02016082e+00  1.74040666e+00]
 [ 0.00000000e+00  7.56421121e-01 -8.38107706e-01]
 [ 0.00000000e+00  2.70367388e-01 -2.87638347e-01]
 [ 1.00000000e+00  3.67578135e-01 -1.71750061e-01]
 [ 0.00000000e+00 -1.18475597e-01  2.20395980e+00]
 [ 0.00000000e+00 -1.47942605e+00 -6.35303205e-01]
 [ 1.00000000e+00 -1.28500455e+00 -1.06988428e+00]
 [ 1.00000000e+00 -1.38221530e+00  4.07691369e-01]
 [ 0.00000000e+00 -1.09058306e+00  7.55356227e-01]
 [ 1.00000000e+00 -1.47942605e+00 -2.00722133e-01]
 [ 1.00000000e+00  9.50842613e-01 -1.06988428e+00]
 [ 1.00000000e+00  9.50842613e-01  5.81523798e-01]
 [ 1.00000000e+00  3.67578135e-

### Train Naive Bayes

In [9]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

In [10]:
classifier.fit(X_train, Y_train)

GaussianNB()

In [11]:
y_pred = classifier.predict(X_test)

In [12]:
result = np.concatenate(
    (y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test), 1)),
    axis = 1
)

In [13]:
result

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0,

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
print('Confusion matrix\n',confusion_matrix(Y_test, y_pred))
print('\nAccuracy Score\n',accuracy_score(Y_test, y_pred))

Confusion matrix
 [[56  2]
 [ 4 18]]

Accuracy Score
 0.925
