## Employee Salary prediction
Here we will be created model for same Position Salary dataset for same business problem. We will see which model will give us the better results

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Position_Salaries.csv')
data.head()

,Position,Level,Salary
0,Business Analyst,1,45000
1,Junior Consultant,2,50000
2,Senior Consultant,3,60000
3,Manager,4,80000
4,Country Manager,5,110000


In [3]:
X = data.iloc[:, 1:-1].values
Y = data.iloc[:, -1].values

print(X)
print(Y)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]


In [12]:
print(X.shape)
print(Y.shape)

(10, 1)
(10,)


### Check missing values

In [5]:
print(data.isnull().sum())

Position    0
Level       0
Salary      0
dtype: int64


### Feature Scaling
Mandat step while using SVR bec it's a distance-based algo.
- Here we are training our model on whole dataset and not splitting it. Hence we will do feature scaling in complete dataset instead of training data.
- But here we have target with regression values, so we will scale these as well.

In [ ]:
# tranform Y from 1D to 2D array - expected format for StandardScalar class
Y = Y.reshape(len(Y), 1)
Y.shape

(10, 1)

In [14]:
print(Y)

[[  45000]
 [  50000]
 [  60000]
 [  80000]
 [ 110000]
 [ 150000]
 [ 200000]
 [ 300000]
 [ 500000]
 [1000000]]


In [15]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler()
X_scaled = X_scaler.fit_transform(X)
print(X_scaled)

[[-1.5666989 ]
 [-1.21854359]
 [-0.87038828]
 [-0.52223297]
 [-0.17407766]
 [ 0.17407766]
 [ 0.52223297]
 [ 0.87038828]
 [ 1.21854359]
 [ 1.5666989 ]]


In [16]:
Y_scaler = StandardScaler()
Y_scaled = Y_scaler.fit_transform(Y)
print(Y_scaled)

[[-0.72004253]
 [-0.70243757]
 [-0.66722767]
 [-0.59680786]
 [-0.49117815]
 [-0.35033854]
 [-0.17428902]
 [ 0.17781001]
 [ 0.88200808]
 [ 2.64250325]]
