### Project 
Here we have dataset of retail company which consist of customer country, age, salary and if they purchased their product or not.

### Importing Libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Importing the Dataset

- iloc for slicing
- using .values we are returning numpy array instead of dataframe by removing col name and index.
<br> Some ML libraries uses numpy instead of df

In [4]:
# creating dataframe named dataset
dataset = pd.read_csv('Data.csv')

X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [5]:
print(X)
print('\n',Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

 ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### Handling Missing data
- Missing data can cause error while training the ML models
- we can use scikit-learn
- If we are using mean or median as strategy, then imputer is applied to column with numeric values. While if we are using most_frequent or constant, we can apply to both numeric and categorical.

In [6]:
from sklearn.impute import SimpleImputer

In [7]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# fit imputer to calculate mean of sec and third column
imputer.fit(X[ :, 1:3])

# apply and replace the calculated value in data             
X[ :, 1:3] = imputer.transform(X[ :, 1:3])

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### Encoding categorical Data

1- Encoding Independent variable


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [9]:
ct = ColumnTransformer(
    transformers = [ 
        ('encoder', OneHotEncoder(drop='first'), [0])
        ],
    remainder = 'passthrough'
)

In [10]:
X = ct.fit_transform(X)
print(type(X))
print('\n',X)

<class 'numpy.ndarray'>

 [[0.0 0.0 44.0 72000.0]
 [0.0 1.0 27.0 48000.0]
 [1.0 0.0 30.0 54000.0]
 [0.0 1.0 38.0 61000.0]
 [1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 35.0 58000.0]
 [0.0 1.0 38.77777777777778 52000.0]
 [0.0 0.0 48.0 79000.0]
 [1.0 0.0 50.0 83000.0]
 [0.0 0.0 37.0 67000.0]]


2- Encoding Target/Dependent Variable

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

In [12]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


### Splitting data into test train dataset

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=1)

In [14]:
print(X_train)
print('\n',X_test)
print('\n',Y_train)
print('\n',Y_test)

[[0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 44.0 72000.0]
 [0.0 1.0 38.0 61000.0]
 [0.0 1.0 27.0 48000.0]
 [0.0 0.0 48.0 79000.0]
 [1.0 0.0 50.0 83000.0]
 [0.0 0.0 35.0 58000.0]]

 [[1.0 0.0 30.0 54000.0]
 [0.0 0.0 37.0 67000.0]]

 [0 1 0 0 1 1 0 1]

 [0 1]


### Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train[:, 2:] = scaler.fit_transform(X_train[:, 2:])
X_test[:, 2:] = scaler.transform(X_test[:, 2:])

In [18]:
print(X_train)
print('\n', X_test)

[[0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [0.0 0.0 1.1475343068237058 1.232653363453549]
 [1.0 0.0 1.4379472069688968 1.5749910381638885]
 [0.0 0.0 -0.7401495441200351 -0.5646194287757332]]

 [[1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [0.0 0.0 -0.44973664397484414 0.2056403393225306]]
